// This file acts as your local database for notes.
// To add a new note:
// 1. Put the PDF file in the `public/notes` folder.
// 2. Add a new object to this array with the correct details.

export const notesData = [
  {
    id: 1,
    title: "Modern Maths Concepts",
    description: "Detailed notes on Modern Maths topics including sequences, series, permutations, and combinations for CAT preparation.",
    section: "qa",
    fileURL: "/notes/modern-maths.pdf",
    createdAt: "2025-07-19",
  },
  {
    id: 2,
    title: "iQuanta Quant Formulae eBook",
    description: "A complete eBook with all essential formulae and concepts for the Quantitative Aptitude section, provided by iQuanta.",
    section: "qa",
    fileURL: "/notes/iQuanta+Quant+Formulae+eBook+.pdf",
    createdAt: "2025-07-19",
  },
  {
    id: 3,
    title: "Basic Algebra Explained",
    description: "Fundamental concepts of Linear and Quadratic Equations, inequalities, and other core algebra topics.",
    section: "qa",
    fileURL: "/notes/Basic-Algebra-final.pdf",
    createdAt: "2025-07-19",
  },
  {
    id: 4,
    title: "Basic Geometry Fundamentals",
    description: "A guide to the fundamentals of geometry, covering lines, triangles, polygons, circles, and mensuration.",
    section: "qa",
    fileURL: "/notes/basic-geometry_final.pdf",
    createdAt: "2025-07-19",
  },
  {
    id: 5,
    title: "Number System Essentials",
    description: "Core concepts of the Number System, including classification, divisibility rules, HCF, LCM, and surds.",
    section: "qa",
    fileURL: "/notes/number-system-final.pdf",
    createdAt: "2025-07-19",
  },
  {
    id: 6,
    title: "Arithmetic Deep Dive",
    description: "In-depth coverage of key arithmetic topics such as mixtures, profit and loss, time & work, and TSD.",
    section: "qa",
    fileURL: "/notes/arithmetic-final.pdf",
    createdAt: "2025-07-19",
  },
  {
    id: 7,
    title: "CAT Vocabulary Builder",
    description: "An extensive alphabetical wordlist designed to build a strong vocabulary for the CAT exam.",
    section: "varc",
    fileURL: "/notes/vocabulart-cat.pdf",
    createdAt: "2025-07-19",
  },
  {
    id: 8,
    title: "Idioms and Phrases Guide",
    description: "A comprehensive guide to common idioms and phrases, essential for the VARC section.",
    section: "varc",
    fileURL: "/notes/Vovabulary-Idioms-and-Phrases-Book.pdf",
    createdAt: "2025-07-19",
  },
  {
    id: 9,
    title: "Vocabulary Tests (A-Z)",
    description: "A series of alphabetical tests to reinforce and assess vocabulary knowledge for CAT.",
    section: "varc",
    fileURL: "/notes/Voabulary-Tests.pdf",
    createdAt: "2025-07-19",
  },
  {
    id: 10,
    title: "1000 Reading Comprehension Passages",
    description: "A large collection of RC passages for extensive practice, covering a wide range of topics.",
    section: "varc",
    fileURL: "/notes/1000-Reading-Comprehension-Passages.pdf",
    createdAt: "2025-07-19",
  },
  {
    id: 11,
    title: "1000 Critical Reasoning Questions",
    description: "Practice questions designed to sharpen critical reasoning and logical deduction skills.",
    section: "varc",
    fileURL: "/notes/1000-Critical-Reasoning-Questions.pdf",
    createdAt: "2025-07-19",
  },
  {
    id: 12,
    title: "1000 Grammar Questions",
    description: "A comprehensive set of grammar questions to master the rules of English usage.",
    section: "varc",
    fileURL: "/notes/1000-Grammar-Questions.pdf",
    createdAt: "2025-07-19",
  },
  {
    id: 13,
    title: "Comprehensive Grammar Rules",
    description: "A detailed guide covering all essential grammar rules, from modifiers to subject-verb agreement.",
    section: "varc",
    fileURL: "/notes/grammar.pdf",
    createdAt: "2025-07-19",
  },
  {
    id: 14,
    title: "VA-RC Cheat Sheets",
    description: "A collection of quick reference cheat sheets for various Verbal Ability and Reading Comprehension topics.",
    section: "varc",
    fileURL: "/notes/VA-RC.pdf",
    createdAt: "2025-07-19",
  },
  {
    id: 15,
    title: "Personal Interview Transcripts",
    description: "A collection of real-life Personal Interview transcripts from IIMs and other top B-schools.",
    section: "varc",
    fileURL: "/notes/PI+Transcript.pdf",
    createdAt: "2025-07-19",
  }
];